apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  creationTimestamp: "2022-08-30T18:47:20Z"
  generation: 1
  managedFields:
  - apiVersion: constraints.gatekeeper.sh/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:enforcementAction: {}
        f:match:
          .: {}
          f:excludedNamespaces: {}
          f:kinds: {}
          f:labelSelector:
            .: {}
            f:matchExpressions: {}
          f:namespaceSelector:
            .: {}
            f:matchExpressions: {}
          f:namespaces: {}
          f:scope: {}
        f:parameters: {}
    manager: agent
    operation: Update
    time: "2022-08-30T18:47:20Z"
  - apiVersion: constraints.gatekeeper.sh/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:byPod: {}
    manager: gatekeeper
    operation: Update
    subresource: status
  name: gitops-rule-2
spec:
  enforcementAction: deny
  match:
    excludedNamespaces: []
    kinds:
    - apiGroups:
      - ""
    labelSelector:
      matchExpressions: []
    namespaceSelector:
      matchExpressions: []
    namespaces:
    - struts
    scope: '*'
  parameters: {}
